/* HALO Presales Navigator. Original discovery framework; product summaries are
   attributed to GTT's public page, reviewed 2026-09-30. No live HALO integration. */
const SOURCE = {title:'GTT Defense Halo — public product overview', url:'https://www.gtt.net/defense-halo/', reviewed:'2026-09-30'};
const MODULES = [
 {id:'config',name:'Recon · Configuration',short:'Configuration',icon:'sliders',summary:'Reviews supported device settings and identifies policy gaps.',verify:'Confirm vendors, versions, access methods and assessment frameworks.'},
 {id:'cve',name:'Recon · CVE',short:'CVE exposure',icon:'shield',summary:'Relates vulnerability information to monitored assets and prioritizes findings.',verify:'Confirm asset matching, vulnerability feeds and refresh intervals.'},
 {id:'detect',name:'Halo Detect',short:'Detection',icon:'radar',summary:'Analyzes supplied logs and flows for unusual activity.',verify:'Confirm telemetry coverage, baselining and measured alert latency.'},
 {id:'response',name:'Halo Response',short:'Response',icon:'bolt',summary:'Runs threat-containment actions on supported devices.',verify:'Confirm actions, authorizations, safeguards and reversal procedures.'}
];
const CUSTOMER = [
 {id:'inventory',group:'Environment',title:'Network & asset inventory',question:'Which locations, devices, cloud accounts and critical assets are in scope?',why:'A defined denominator is essential. Missing inventory cannot be interpreted as complete visibility.',evidence:'A dated inventory including device models, software versions, owners and excluded assets.',follow:'Separate assets you own from those operated by a third party. Identify a representative pilot subset.',owner:'Network architect',modules:['config','cve','detect'],gtt:'compatibility',hint:'Capture counts only when sourced; otherwise record “unknown”.'},
 {id:'firewalls',group:'Environment',title:'Firewalls & network controls',question:'Which firewall, router and SD-WAN vendors and versions protect the in-scope sites?',why:'A vendor name alone is not proof of compatibility with a specific HALO capability.',evidence:'Device/version list, management access method and operational owner.',follow:'For each device, ask separately about assessment, telemetry collection and response actions.',owner:'Network / security engineering',modules:['config','response'],gtt:'compatibility',hint:'Selecting a vendor does not assert HALO support.'},
 {id:'cloud',group:'Environment',title:'Cloud & hybrid footprint',question:'Where are workloads hosted, and which network paths bypass the corporate network?',why:'Cloud-to-cloud, remote-user and internal traffic may require separate observation points.',evidence:'Cloud account inventory, routing overview, flow-log availability and collection restrictions.',follow:'Name the cloud owner and identify paths that are outside the intended pilot.',owner:'Cloud architect',modules:['detect','cve'],gtt:'coverage',hint:'Do not assume backbone visibility covers cloud or east-west traffic.'},
 {id:'critical',group:'Environment',title:'Critical business services',question:'Which applications cannot tolerate isolation, interruption or configuration changes?',why:'Containment can affect business availability; critical services require explicit exclusions and approvals.',evidence:'Business-service list, owner contacts, dependency notes and change windows.',follow:'Ask who is allowed to approve containment for each critical service.',owner:'Application / business owner',modules:['response'],gtt:'safeguards',hint:'Business criticality is customer-defined, not generated from tool counts.'},
 {id:'telemetry',group:'Visibility',title:'Available logs & network flows',question:'Which logs, flows, device configurations and identity events can the customer provide?',why:'Detection and correlation depend on the data actually delivered, not simply the number of installed tools.',evidence:'Source inventory, sample field list, delivery frequency, retention and access owner.',follow:'Check permissions, data quality, timestamps and export constraints before proposing collection.',owner:'SOC / platform engineering',modules:['detect','config'],gtt:'telemetry',hint:'Record source type and scope; do not paste raw logs or secrets here.'},
 {id:'eastwest',group:'Visibility',title:'East-west & encrypted traffic',question:'How is internal movement observed, and what is visible when traffic is encrypted?',why:'Encrypted payloads and unobserved segments impose limits that must be stated explicitly.',evidence:'Observation-point map and known blind spots for internal, remote and encrypted traffic.',follow:'Ask GTT which metadata is sufficient and what cannot be detected in that scope.',owner:'Security architect',modules:['detect'],gtt:'coverage',hint:'Network visibility is not equivalent to inspecting every payload.'},
 {id:'siem',group:'Visibility',title:'SIEM / NDR / SOC operating model',question:'Which tools and teams correlate alerts today, and where does investigation move between systems?',why:'Compare the actual stack. Existing tools may already provide correlation, detection and automation.',evidence:'Current SIEM/NDR tools, monitored sources, SOC ownership and example investigation steps.',follow:'Identify duplication and desired handoff; do not lead with a replacement assumption.',owner:'SOC manager',modules:['detect','response'],gtt:'integrations',hint:'Record what works well as carefully as the gaps.'},
 {id:'endpoint',group:'Visibility',title:'Endpoint & identity controls',question:'Which EDR, identity and access controls are in place, and what information can be shared?',why:'Agentless network observation does not establish replacement of endpoint or identity protection.',evidence:'Control inventory, supported export mechanisms and customer integration policy.',follow:'Define complementary use cases and controls that remain in place.',owner:'Endpoint / identity owner',modules:['detect'],gtt:'boundaries',hint:'Keep endpoint prevention and identity enforcement in the comparison.'},
 {id:'configuration',group:'Posture & exposure',title:'Configuration review process',question:'How often are device settings reviewed, and how are findings assigned and closed?',why:'The opportunity is an evidenced gap in review coverage or cadence, not an assumption that reviews are manual.',evidence:'Latest review, applicable configuration standard, cadence, backlog and remediation owner.',follow:'Choose a small approved device sample and define what a useful finding looks like.',owner:'Network security lead',modules:['config'],gtt:'frameworks',hint:'A policy finding is not automatically a confirmed vulnerability.'},
 {id:'vulnerabilities',group:'Posture & exposure',title:'Vulnerability prioritization',question:'How are CVEs matched to assets and ranked against exposure and business importance?',why:'A high CVE count alone does not establish reachable or exploitable risk.',evidence:'An anonymized triage example, inventory source, prioritization criteria and patch SLA.',follow:'Ask about false asset matches, exceptions and finding validation.',owner:'Vulnerability manager',modules:['cve'],gtt:'cve',hint:'Keep asset matching, reachability and exploitation evidence distinct.'},
 {id:'baselines',group:'Posture & exposure',title:'Measured detection & response times',question:'What is the measured time from detection to analyst review, authorization and containment?',why:'A target is only meaningful against an agreed measurement definition and observed baseline.',evidence:'Dated incident samples with start/end definitions, sample size and relevant percentiles.',follow:'Separate collection delay, alert creation, investigation and action completion.',owner:'SOC performance owner',modules:['detect','response'],gtt:'latency',hint:'Do not convert “network speed” into an invented customer SLA.'},
 {id:'audit',group:'Posture & exposure',title:'Audit evidence & policy requirements',question:'Which policy frameworks and evidence requirements must the proposed assessment address?',why:'A report may assist an audit but does not by itself establish compliance or certification.',evidence:'Customer control list, evidence format, review cadence and audit owner.',follow:'Ask GTT for a sample report mapped to the exact requested controls.',owner:'Risk / compliance lead',modules:['config'],gtt:'frameworks',hint:'Avoid “compliant” unless the relevant assessment supports it.'},
 {id:'response',group:'Authority & outcomes',title:'Response approval & rollback',question:'Who can authorize each containment action, and what must happen before it is reversed?',why:'Automated containment requires explicit operational authority and an agreed recovery process.',evidence:'Action/approval matrix, change policy, exclusions, rollback steps and named owners.',follow:'Distinguish observe-only, recommendation, approval-gated and automated modes as requested options.',owner:'Incident commander',modules:['response'],gtt:'safeguards',hint:'Requested modes are not a statement that HALO supports each mode.'},
 {id:'data',group:'Authority & outcomes',title:'Data handling & collection consent',question:'What data may leave the environment, where may it be processed, and who approves collection?',why:'Network telemetry can contain sensitive information. Collection needs explicit scope and appropriate controls.',evidence:'Approved data categories, residency/retention requirements and security review owner.',follow:'Do not collect production secrets or raw telemetry in this presales application.',owner:'Privacy / security review',modules:['config','cve','detect','response'],gtt:'isolation',hint:'This navigator stores browser-local notes; it is not a telemetry platform.'},
 {id:'outcomes',group:'Authority & outcomes',title:'Executive outcomes & success criteria',question:'Which measurable outcome would justify a pilot, and who decides whether it succeeded?',why:'Commercial relevance comes from customer-approved outcomes, not generic risk or savings scores.',evidence:'Named sponsor, prioritized outcomes, baseline, proposed target and measurement method.',follow:'Agree what remains unchanged in the current security stack during the pilot.',owner:'Executive sponsor',modules:['config','cve','detect','response'],gtt:'proof',hint:'Targets remain hypotheses until the pilot measures them.'},
 {id:'commercial',group:'Authority & outcomes',title:'Buying process & service scope',question:'Who owns budget and procurement, and what scope, timing and exclusions must be defined?',why:'Technical fit does not establish pricing, contract terms or availability.',evidence:'Buying team, evaluation window, scope assumptions and required commercial approvals.',follow:'Ask GTT to confirm licensing units, service responsibilities and actual availability.',owner:'Account team / customer sponsor',modules:['config','cve','detect','response'],gtt:'service',hint:'Do not infer a price or included feature from a public product page.'}
];
const GTT = [
 {id:'compatibility',group:'Technical fit',title:'Device & version compatibility',question:'Which customer devices and software versions support each proposed HALO capability?',owner:'GTT product / solutions engineering',needed:'Current supported-device matrix, exact versions, per-module limitations and written scope confirmation.',accept:'Every pilot device is mapped separately to assessment, telemetry and response support.',customer:'inventory',modules:['config','cve','detect','response'],critical:true},
 {id:'telemetry',group:'Technical fit',title:'Ingestion & source requirements',question:'Which source formats, fields, permissions, volumes and delivery intervals are required?',owner:'GTT implementation / product engineering',needed:'Integration guide, required fields, sizing limits, sample validation and source-health criteria.',accept:'Sample data is validated and missing fields or sources are explicitly excluded.',customer:'telemetry',modules:['detect','cve','config'],critical:true},
 {id:'collectors',group:'Technical fit',title:'Collector placement & connectivity',question:'Where will collection run, and what changes, connectivity and access are required?',owner:'GTT solution architect',needed:'Deployment design, network paths, access requirements, customer tasks and off-network prerequisites.',accept:'The customer accepts placement and connectivity, including environments outside GTT transport.',customer:'cloud',modules:['config','cve','detect','response'],critical:true},
 {id:'coverage',group:'Technical fit',title:'Visibility boundaries & exclusions',question:'What can be observed for east-west, encrypted, cloud and remote-user traffic?',owner:'GTT product security architect',needed:'A coverage map tied to actual sources, encrypted-traffic limitations and unsupported paths.',accept:'No “all traffic” or complete-coverage statement unless independently demonstrated in scope.',customer:'eastwest',modules:['detect'],critical:true},
 {id:'integrations',group:'Technical fit',title:'Existing-tool integrations',question:'Which documented APIs and connectors support the customer’s specific tools and workflows?',owner:'GTT integrations engineering',needed:'Current API/connector documentation, supported actions, directionality and required licenses.',accept:'A test event reaches the intended destination with agreed fields and ownership.',customer:'siem',modules:['detect','response'],critical:false},
 {id:'cve',group:'Evidence & performance',title:'CVE matching & prioritization',question:'How are assets matched, feeds updated, scores explained and false matches corrected?',owner:'GTT product / threat research',needed:'Matching methodology, feed freshness, context requirements and explainable sample results.',accept:'Known examples and exclusions are reviewed with the customer’s vulnerability owner.',customer:'vulnerabilities',modules:['cve'],critical:true},
 {id:'frameworks',group:'Evidence & performance',title:'Configuration frameworks & reports',question:'Which frameworks, controls and device-specific checks are supported in the proposed service?',owner:'GTT product / security assurance',needed:'Dated control mapping, sample report, check coverage and exception-handling process.',accept:'The customer accepts the scope and does not mistake assessment output for certification.',customer:'configuration',modules:['config'],critical:false},
 {id:'latency',group:'Evidence & performance',title:'Baselining, latency & false positives',question:'What are the measured baselining period, latency definitions, performance bounds and tuning process?',owner:'GTT product / service engineering',needed:'Test methodology, scope/conditions, latency distribution, false-positive handling and any contractual commitments.',accept:'Pilot measurements use agreed definitions; marketing descriptions are not treated as SLAs.',customer:'baselines',modules:['detect','response'],critical:false},
 {id:'isolation',group:'Governance & authority',title:'Tenant isolation & access controls',question:'How are customer data, processing and administrator access separated and audited?',owner:'GTT security assurance',needed:'Security architecture, access/RBAC model, tenant-boundary evidence and relevant assurance reports.',accept:'Customer security review accepts the documented isolation and privileged-access model.',customer:'data',modules:['config','cve','detect','response'],critical:true},
 {id:'residency',group:'Governance & authority',title:'Residency, retention & AI data use',question:'Where is data stored/processed, how long is it retained, and is it used to train or improve models?',owner:'GTT privacy / security assurance',needed:'Service-specific data handling terms, regions, retention/deletion controls, subprocessors and model-use restrictions.',accept:'Documented treatment is accepted by the customer; no assumption that tenant isolation answers training-use questions.',customer:'data',modules:['config','cve','detect','response'],critical:true},
 {id:'safeguards',group:'Governance & authority',title:'Response modes, approval & rollback',question:'Which actions and operating modes are supported, who authorizes them, and how can they be stopped or reversed?',owner:'GTT product / service engineering',needed:'Supported runbooks, permission boundaries, approval behavior, audit trail, exclusions and tested rollback.',accept:'No production action without agreed authority, safeguards and a validated recovery procedure.',customer:'response',modules:['response'],critical:true},
 {id:'boundaries',group:'Governance & authority',title:'Service and control boundaries',question:'What does HALO complement, what does it not replace, and who owns investigation and remediation?',owner:'GTT product / service owner',needed:'Responsibility matrix and explicit boundaries relative to EDR, SIEM, NDR, SOAR and vulnerability tools.',accept:'GTT and customer owners agree handoffs; no generic replacement claim is made.',customer:'endpoint',modules:['config','cve','detect','response'],critical:true},
 {id:'proof',group:'Evidence & performance',title:'Pilot proof & acceptance',question:'Which claims can be demonstrated safely with representative customer data and an agreed success measure?',owner:'GTT solution architect',needed:'Pilot scope, dates, baseline method, success measures, exclusions and named sign-off owners.',accept:'Success criteria are proposed and jointly reviewed before any pilot begins.',customer:'outcomes',modules:['config','cve','detect','response'],critical:true},
 {id:'service',group:'Commercial scope',title:'Availability, licensing & responsibilities',question:'What is available for this customer now, how is it licensed, and what exactly is included?',owner:'GTT product / commercial owner',needed:'Approved service description, current availability, scope/exclusions, licensing basis and commercial approval.',accept:'No feature, support entitlement, price or service level is promised without approved terms.',customer:'commercial',modules:['config','cve','detect','response'],critical:true}
];
const STACK = [
 {id:'firewall',title:'Firewall & network policy',retained:'Traffic enforcement and existing network controls.',halo:'Configuration assessment; eligible response actions.',module:'config',need:'Device/version and action support.'},
 {id:'vulnerability',title:'Vulnerability management',retained:'Scanning, patch workflow and asset verification.',halo:'Asset-linked CVE assessment and prioritization.',module:'cve',need:'Asset matching, feed scope and overlap.'},
 {id:'ndr',title:'Network detection / NDR',retained:'Existing network sensors and detection workflows.',halo:'Analysis of the logs and flows provided.',module:'detect',need:'Actual coverage and comparative test results.'},
 {id:'siem',title:'SIEM & SOC',retained:'Existing event management and SOC investigation.',halo:'Correlated findings and integration opportunities.',module:'detect',need:'Connector capabilities and handoff ownership.'},
 {id:'soar',title:'SOAR & response automation',retained:'Existing playbooks and approved control actions.',halo:'Supported threat-containment runbooks.',module:'response',need:'Action overlap, approvals and rollback.'},
 {id:'edr',title:'Endpoint detection / EDR',retained:'Endpoint-specific prevention and investigation.',halo:'Network-layer context; do not assume replacement.',module:'detect',need:'Evidence of complementarity and integration.'},
 {id:'identity',title:'Identity & access controls',retained:'Authentication, authorization and identity enforcement.',halo:'Potential correlation with available identity data.',module:'detect',need:'Specific sources, fields and supported use cases.'},
 {id:'cloud',title:'Cloud security posture',retained:'Cloud-specific configuration and workload controls.',halo:'Assess only the explicitly supported cloud inputs.',module:'config',need:'Service-specific support and visibility exclusions.'}
];
const OPPORTUNITIES = [
 {id:'config',title:'Configuration assurance',icon:'sliders',tag:'Recon · Configuration',signal:['configuration','audit','firewalls'],proof:['compatibility','frameworks','collectors'],story:'Test whether a scoped assessment can surface actionable configuration issues beyond the existing review process.',test:'Compare a sample of approved devices against agreed controls. Validate finding accuracy and review effort.',metric:'Validated actionable findings; review effort per device.'},
 {id:'cve',title:'Exposure prioritization',icon:'shield',tag:'Recon · CVE',signal:['vulnerabilities','inventory'],proof:['compatibility','cve','telemetry'],story:'Test whether additional asset context helps the customer prioritize an agreed sample of vulnerabilities.',test:'Review a matched-asset sample with the vulnerability owner. Record false matches and priority changes.',metric:'Asset-match accuracy; accepted priority changes; triage effort.'},
 {id:'detect',title:'Network detection context',icon:'radar',tag:'Halo Detect',signal:['telemetry','eastwest','siem','baselines'],proof:['telemetry','coverage','latency','integrations'],story:'Test a defined visibility gap or investigation use case alongside the customer’s existing detection stack.',test:'Use approved benign test activity and compare evidence, source coverage, latency and analyst interpretation.',metric:'Agreed use-case coverage; measured alert latency; analyst acceptance.'},
 {id:'response',title:'Governed containment',icon:'bolt',tag:'Halo Response',signal:['response','critical','baselines'],proof:['compatibility','safeguards','boundaries','latency'],story:'Evaluate whether supported actions can shorten an authorized containment process without unacceptable disruption.',test:'Begin with a non-production or explicitly approved controlled exercise. Validate authorization and rollback.',metric:'Authorization-to-containment time; action correctness; recovery result.'}
];
const PILOT_TASKS = [
 {id:'scope',title:'Representative scope & exclusions agreed',help:'List exact sites, sources, assets and excluded controls.'},
 {id:'authority',title:'Customer collection authority recorded',help:'Record who approved what data can be shared. This checkbox does not grant authorization.'},
 {id:'gtt',title:'Applicable HALO support evidenced',help:'Resolve the relevant product validation items. This checkbox alone does not close them.'},
 {id:'baseline',title:'Baseline & measurement method agreed',help:'Define timing boundaries, sample size and how the existing stack will be compared.'},
 {id:'success',title:'Acceptance criteria & owners agreed',help:'Set measurable targets as hypotheses and identify sign-off owners.'},
 {id:'safety',title:'Action safeguards & rollback reviewed',help:'For Response, validate permissions, exclusions and a reversible test before any action.'},
 {id:'data',title:'Data handling & deletion reviewed',help:'Document regions, retention, permitted use and deletion expectations.'},
 {id:'review',title:'Executive readout & decision date agreed',help:'Choose a review date and document the intended decision, not a predetermined outcome.'}
];
const NAV = [
 ['overview','Overview','grid'],['discovery','Customer discovery','search'],['readiness','GTT / HALO validation','shieldcheck'],['stack','Security stack comparison','layers'],['executive','Executive experience','chart'],['opportunities','Strategic opportunities','target'],['pilot','Pilot definition','flag'],['output','Briefs & evidence','file']
];
const C_STATUS = [['unknown','Not assessed'],['gap','Gap reported'],['partial','Partially addressed'],['adequate','Adequately addressed'],['na','Out of scope']];
const G_STATUS = [['open','Open question'],['review','In review'],['evidenced','Evidence recorded'],['unsupported','Unsupported / blocked'],['na','Not applicable']];
const COVERAGE = [['unknown','Unknown'],['strong','Well covered'],['partial','Partial coverage'],['gap','Known gap'],['na','Out of scope']];
